### ISSUE TITLE
As a new user I want to register myself so that I can login to the system

### ISSUE THREAD

**Issue by pet-ads** [pet-ads/systematic-front#32]
# Task 

- [ ] Configure CORS to accept request from front end IP [#70](https://github.com/pet-ads/systematic/issues/70)
- [ ] Integrate front end to back end

# Acceptance criteria
- [ ] Given no user of same username already exists, When I submit my registration data, Then the system should confirmation that I have been registered.
- [ ] Given a user of same username is already registered in the system, When I submit my registration data, Then the system should provide an error message informing the user is already registered. 
- [ ] Given I provide incomplete form data, When I submit my registration, Then the system should inform which form data is incomplete.
- [ ]  Given I provide different password confirmation, When I submit my registration, Then the system should inform the password does not match its confirmation.
