### ISSUE TITLE
Como novo usuário, eu quero me registrar no sistema, para que eu possa me autenticar.

### ISSUE THREAD

**Issue by lucas-ifsp** [pet-ads/systematic-front#37]
## Tasks

- [x] Não fazer requisição se o form não estiver correto
- [x] Indicar usuário repetido como mensagem no form
- [x] Resolver bug do botão de envio. 
- [x] Reposicionar toast ao centro.
- [x] Ajustar usabilidade do modal para caber na mesma tela.
- [x] Montar hook #63 
- [x] Reformular ui #62 
- [x] Configurar CORS [70] (https://github.com/pet-ads/systematic/issues/70)
- [x] Revisar e melhorar documentação do Swagger [75] (https://github.com/pet-ads/systematic/issues/75)
- [x] Ajustar o link de redirecionamento do forgot password
- [x] colocar o toast abaixo do botão de login
- [x] Bloquear o botão de submit quando ele for clickado

## Acceptance criteria
- [x] Dado que um username ainda não existe, quando eu submeto meu formulário, então o sistema deve informar que o cadastro foi realizado com sucesso.
- [x] Dado que um username ou o email já existe no sistema, quando eu submeto meu formulário, então o sistema deve fornecer uma mensagem de erro dizendo que o username ou email já está em uso.
- [x] O usuário só deve poder acessar a página de login caso seus tokens tenham expirado, ou feito logout
- [x] Dado que eu forneci um formulário incompleto ou com dados incorretos, quando eu submeto o formulário, então o sistema deve fornecer uma mensagem indicando quais campos estão incompletos ou incorretos.
- [x] Dado que eu forneci uma confirmação de senha diferente da senha, quando eu submeto o formulário, então o sistema deve fornecer uma mensagem informando que as senhas não conferem.
- [x] Dado que estou autenticado, quando digito manualmente o endereço da home, então gostaria acessar o conteúdo inicial, mas continuar autenticado e vendo meu nome no botão de acesso.
- [x] Dado que o login ocorreu com sucesso, quando acesso o sistema, gostaria apenas de ver a página inicial sem mensagens adicionais.

**Comment by ericksgmes** [comment]
Swagger é a issue 75 não 71

**Comment by lucas-ifsp** [comment]
Prover mensagem descritiva para erro de usuário ou email já em uso.

Apresentar em uma mensagens múltiplos erros existentes.
