### ISSUE TITLE
Como usuário registrado, eu quero me autenticar no sistema, para que eu possa acessar as funcionalidades.

### ISSUE THREAD

**Issue by lucas-ifsp** [pet-ads/systematic-front#38]
Task: 

- [x]  Revisar Swagger [#76](https://github.com/pet-ads/systematic/issues/76)
- [x] Adicionar/revisar presenter/hateoas [#77](https://github.com/pet-ads/systematic/issues/77)
-  [x] Atualizar layout do login #64 
-  [x] Armazenar os tokens de resposta de forma segura #65 
-  [x] Realizar requisição e redirecionamento da página  #66 

## Teste de aceitação
- [x] Dado que forneci usuário e senha corretos, quando submeto o formulário, então devo ser redirecionado para a tela na qual vejo todos meus estudos sistemáticos.
- [x] Dado que forneci usuário ou senha inválidos, quando submeto o formulário, então ser informado que o usuário OU a senha estão errados e os campos de usuário e senha foram apagados.
- [x] Dado que não forneci usuário ou senha, quando submeto o formulário, então o sistema imediatamente me informa da ausência de um dos campos.

**Comment by lucas-ifsp** [comment]
- Só pode sair se o usuário deslogar. 

- Precisa dar mensagem de usuário ou senha inválido

- Dar mensagem ou indicar campo ausente.

**Comment by lucas-ifsp** [comment]
Sobre swagger: 

- Revisar os links do swagger para hateoas

Sobre hateoas: 

- Incluir os verbos
- Double check nos nomes dos campos do link
- Arrumar o hateoas do GET de systematic study
-
